"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Submission={id:string;owner_name:string;owner_phone:string;owner_email:string|null;city:string;property_type:string;locality:string;address:string|null;expected_rent:string;deposit:string|null;maintenance:string|null;bedrooms:number|null;bathrooms:number|null;area_sqft:number|null;furnishing:string|null;available_from:string|null;amenities:string[];description:string|null;image_urls:string[];status:string;approved_property_id:string|null;created_at:string};
const reviewStatuses=["pending","contacted","approved","rejected"];

export default function OwnerSubmissionsPage(){
  const [loading,setLoading]=useState(true),[allowed,setAllowed]=useState(false),[items,setItems]=useState<Submission[]>([]),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{if(!supabase)return;const {data}=await supabase.from("owner_submissions").select("*").order("created_at",{ascending:false});setItems((data||[]) as Submission[])},[]);
  useEffect(()=>{(async()=>{if(!supabase){setLoading(false);return}const {data:{session}}=await supabase.auth.getSession();if(session){const {data}=await supabase.from("admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();setAllowed(Boolean(data));if(data)await load()}setLoading(false)})()},[load]);
  async function updateStatus(id:string,status:string){if(!supabase)return;const {error}=await supabase.from("owner_submissions").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error){setNotice(error.message);return}setItems(v=>v.map(x=>x.id===id?{...x,status}:x))}
  async function approve(item:Submission){if(!supabase||item.approved_property_id)return;setNotice("Creating a draft property…");const code=`OWN-${Date.now().toString().slice(-6)}`;const specs=[item.bedrooms?`${item.bedrooms} Beds`:"",item.bathrooms?`${item.bathrooms} Baths`:"",item.area_sqft?`${item.area_sqft} sq.ft`:""].filter(Boolean);const {data,error}=await supabase.from("properties").insert({property_code:code,title:`${item.property_type} for rent in ${item.locality}`,city:item.city,property_type:item.property_type,locality:`${item.locality}, ${item.city}`,rent:item.expected_rent,deposit:item.deposit,maintenance:item.maintenance,bedrooms:item.bedrooms,bathrooms:item.bathrooms,area_sqft:item.area_sqft,furnishing:item.furnishing,available_from:item.available_from,address:item.address,address_visibility:"approximate",amenities:item.amenities||[],restrictions:[],description:item.description,specs,badge:"Owner listed",availability:item.available_from?`From ${item.available_from}`:"Ready now",image_url:item.image_urls?.[0]||null,image_urls:item.image_urls||[],status:"draft"}).select("id").single();if(error){setNotice(error.message);return}await supabase.from("owner_submissions").update({status:"approved",approved_property_id:data.id,updated_at:new Date().toISOString()}).eq("id",item.id);setNotice("Approved and added to Properties as a draft. Review it before publishing.");await load()}
  async function remove(id:string){if(!supabase||!confirm("Delete this owner submission permanently?"))return;await supabase.from("owner_submissions").delete().eq("id",id);setItems(v=>v.filter(x=>x.id!==id))}
  if(loading)return <main className="admin-shell"><div className="admin-login">Loading…</div></main>;
  if(!allowed)return <main className="admin-shell"><div className="admin-login"><h1>Admin access required</h1><p>Please sign in through the main dashboard first.</p><Link href="/admin">Open admin login</Link></div></main>;
  const pending=items.filter(x=>x.status==="pending").length;
  return <main className="dashboard"><aside><div className="brand light"><span className="brand-mark">P</span><span>Pixellar <b>Spaces</b></span></div><nav><Link href="/admin">Enquiries & properties</Link><Link className="active" href="/admin/owners">Owner submissions <b>{pending}</b></Link></nav><Link href="/list-your-property">View owner form ↗</Link><Link href="/">View public website ↗</Link></aside><section className="dash-main"><header><div><span className="kicker">OWNER PIPELINE</span><h1>Property submissions</h1><p>Verify every owner and property before publishing.</p></div></header>{notice&&<div className="dash-notice">{notice}</div>}<div className="stat-grid"><div><small>Total submissions</small><strong>{items.length}</strong></div><div><small>Pending review</small><strong>{pending}</strong></div><div><small>Approved</small><strong>{items.filter(x=>x.status==="approved").length}</strong></div><div><small>Rejected</small><strong>{items.filter(x=>x.status==="rejected").length}</strong></div></div><div className="owner-submission-list">{items.length?items.map(item=><article className="owner-submission-card" key={item.id}><div className="owner-submission-head"><div><span className="lead-type">OWNER</span><h2>{item.property_type} in {item.locality}</h2><p>{item.owner_name} · {item.owner_phone}{item.owner_email?` · ${item.owner_email}`:""}</p></div><select value={item.status} onChange={e=>updateStatus(item.id,e.target.value)}>{reviewStatuses.map(s=><option key={s}>{s}</option>)}</select></div>{item.image_urls?.length>0&&<div className="owner-photo-strip">{item.image_urls.map(url=><img key={url} src={url} alt="Owner submitted property"/>)}</div>}<div className="owner-detail-grid"><div><small>Location</small><b>{item.locality}, {item.city}</b></div><div><small>Expected rent</small><b>{item.expected_rent}</b></div><div><small>Property</small><b>{[item.bedrooms&&`${item.bedrooms} bed`,item.bathrooms&&`${item.bathrooms} bath`,item.area_sqft&&`${item.area_sqft} sq.ft`].filter(Boolean).join(" · ")||item.property_type}</b></div><div><small>Furnishing</small><b>{item.furnishing||"Not specified"}</b></div></div>{item.description&&<p className="owner-description">{item.description}</p>}<div className="owner-actions"><a href={`https://wa.me/91${item.owner_phone.replace(/\D/g,"").slice(-10)}?text=${encodeURIComponent(`Hello ${item.owner_name}, this is Pixellar Spaces regarding your ${item.property_type.toLowerCase()} in ${item.locality}.`)}`} target="_blank">WhatsApp owner</a>{!item.approved_property_id&&item.status!=="rejected"&&<button className="orange-btn" onClick={()=>approve(item)}>Approve → create draft</button>}{item.approved_property_id&&<Link href="/admin">Draft created — open Properties</Link>}<button className="danger-link" onClick={()=>remove(item.id)}>Delete</button></div></article>):<div className="dash-empty">No owner submissions yet.</div>}</div></section></main>;
}
