"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";

type Lead = { id:string; lead_type:string; property_title:string|null; full_name:string; phone:string; city:string; space_type:string; locality_budget:string|null; details:string|null; status:string; created_at:string; scheduled_at:string|null; visit_notes:string|null; cancellation_reason:string|null };
type Property = { id:string; property_code:string; title:string; city:string; property_type:string; locality:string; rent:string; specs:string[]; badge:string; availability:string; status:string; image_url:string|null; verified:boolean; verified_at:string|null };
type Tab = "leads"|"visits"|"properties"|"analytics";
const statuses=["new","contacted","visit_scheduled","qualified","closed","lost"];
const fmt=(value:string)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date(value));
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;

export default function AdminPage(){
 const [loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[allowed,setAllowed]=useState(false);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[notice,setNotice]=useState("");
 const [tab,setTab]=useState<Tab>("leads"),[leads,setLeads]=useState<Lead[]>([]),[properties,setProperties]=useState<Property[]>([]);

 const loadData=useCallback(async()=>{if(!supabase)return;const [{data:l},{data:p}]=await Promise.all([supabase.from("leads").select("*").order("created_at",{ascending:false}),supabase.from("properties").select("*").order("created_at",{ascending:false})]);setLeads((l||[]) as Lead[]);setProperties((p||[]) as Property[])},[]);
 useEffect(()=>{(async()=>{if(!supabase){setLoading(false);return}const {data:{session}}=await supabase.auth.getSession();setSignedIn(Boolean(session));if(session){const {data}=await supabase.from("admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();setAllowed(Boolean(data));if(data)await loadData()}setLoading(false)})()},[loadData]);
 async function login(e:FormEvent){e.preventDefault();if(!supabase)return;setNotice("Signing in…");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setNotice(error.message);return}const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",data.user.id).maybeSingle();setSignedIn(true);setAllowed(Boolean(admin));setNotice(admin?"":"This account is not authorized.");if(admin)await loadData()}
 async function updateLead(id:string,changes:Partial<Lead>){if(!supabase)return;const {error}=await supabase.from("leads").update(changes).eq("id",id);if(error){setNotice(error.message);return}setLeads(v=>v.map(x=>x.id===id?{...x,...changes}:x));setNotice("Visit details saved.")}
 async function verifyProperty(p:Property){if(!supabase)return;const changes={verified:!p.verified,verified_at:!p.verified?new Date().toISOString():null,badge:!p.verified?"Verified":p.badge==="Verified"?"Listed":p.badge};const {error}=await supabase.from("properties").update(changes).eq("id",p.id);if(error){setNotice(error.message);return}setProperties(v=>v.map(x=>x.id===p.id?{...x,...changes}:x))}
 function downloadCSV(){const rows=[["Lead ID","Type","Name","Phone","City","Locality / Budget","Property","Status","Visit date","Created"],...leads.map(l=>[l.id,l.lead_type,l.full_name,l.phone,l.city,l.locality_budget,l.property_title,l.status,l.scheduled_at?fmt(l.scheduled_at):"",fmt(l.created_at)])];const blob=new Blob(["\uFEFF"+rows.map(r=>r.map(csvCell).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`pixellar-spaces-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const visits=useMemo(()=>leads.filter(x=>x.lead_type==="visit").sort((a,b)=>(a.scheduled_at||"9999").localeCompare(b.scheduled_at||"9999")),[leads]);
 const localityRows=useMemo(()=>Object.entries(leads.reduce<Record<string,number>>((a,l)=>{const k=(l.locality_budget||l.city||"Unspecified").split(",").pop()?.trim()||"Unspecified";a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[leads]);
 const closed=leads.filter(x=>x.status==="closed").length, conversion=leads.length?Math.round(closed/leads.length*100):0, upcoming=visits.filter(x=>x.scheduled_at&&new Date(x.scheduled_at)>=new Date()&&x.status!=="closed"&&x.status!=="lost");
 if(loading)return <main className="admin-shell"><div className="admin-login">Loading…</div></main>;
 if(!isSupabaseConfigured)return <main className="admin-shell"><div className="admin-login"><h1>Connect Supabase first</h1><Link href="/">← Website</Link></div></main>;
 if(!signedIn||!allowed)return <main className="admin-shell"><form className="admin-login" onSubmit={login}><div className="brand"><span className="brand-mark">P</span><span>Pixellar <b>Spaces</b></span></div><span className="kicker">SECURE TEAM ACCESS</span><h1>Admin dashboard</h1><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{notice&&<div className="admin-notice">{notice}</div>}<button className="orange-btn">Sign in</button></form></main>;
 return <main className="dashboard update4"><aside><div className="brand light"><span className="brand-mark">P</span><span>Pixellar <b>Spaces</b></span></div><nav><button className={tab==="leads"?"active":""} onClick={()=>setTab("leads")}>Enquiries <b>{leads.filter(x=>x.status==="new").length}</b></button><button className={tab==="visits"?"active":""} onClick={()=>setTab("visits")}>Visit calendar <b>{upcoming.length}</b></button><button className={tab==="properties"?"active":""} onClick={()=>setTab("properties")}>Verification <b>{properties.filter(x=>x.verified).length}</b></button><button className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>Analytics</button><Link href="/admin/owners">Owner submissions →</Link></nav><Link href="/">View public website ↗</Link><button className="logout" onClick={()=>supabase?.auth.signOut().then(()=>location.reload())}>Sign out</button></aside><section className="dash-main"><header><div><span className="kicker">OPERATIONS CENTER · UPDATE 4</span><h1>{tab==="leads"?"Enquiries & follow-up":tab==="visits"?"Visit scheduling":tab==="properties"?"Property verification":"Analytics & reports"}</h1></div>{tab==="analytics"&&<button className="orange-btn" onClick={downloadCSV}>Download CSV</button>}</header>{notice&&<div className="dash-notice">{notice}</div>}
 {tab==="leads"&&<><div className="stat-grid"><div><small>Total leads</small><strong>{leads.length}</strong></div><div><small>New</small><strong>{leads.filter(x=>x.status==="new").length}</strong></div><div><small>Visits</small><strong>{visits.length}</strong></div><div><small>Closed</small><strong>{closed}</strong></div></div><div className="data-card"><div className="data-head"><b>Recent enquiries</b><span>Newest first</span></div>{leads.map(l=><article className="lead-row" key={l.id}><div className="lead-type">{l.lead_type.toUpperCase()}</div><div><strong>{l.full_name}</strong><span>{l.phone} · {l.city}</span><small>{l.property_title||l.locality_budget||"General enquiry"}</small></div><select value={l.status} onChange={e=>updateLead(l.id,{status:e.target.value})}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select><a href={`https://wa.me/91${l.phone.replace(/\D/g,"").slice(-10)}`} target="_blank">WhatsApp</a></article>)}</div></>}
 {tab==="visits"&&<div className="visit-layout"><div className="calendar-list"><div className="data-head"><b>Upcoming visits</b><span>{upcoming.length} scheduled</span></div>{upcoming.length?upcoming.map(l=><VisitCard key={l.id} lead={l} update={updateLead}/>):<div className="dash-empty">No upcoming visits scheduled.</div>}</div><div className="calendar-list"><div className="data-head"><b>Unscheduled requests</b><span>Set date & time</span></div>{visits.filter(x=>!x.scheduled_at&&x.status!=="closed").map(l=><VisitCard key={l.id} lead={l} update={updateLead}/>)}</div></div>}
 {tab==="properties"&&<div className="data-card"><div className="data-head"><b>Property verification</b><span>Verify only after document/site checks</span></div>{properties.map(p=><article className="property-row" key={p.id}><div className="property-code">{p.property_code}</div><div><strong>{p.title}</strong><span>{p.locality} · {p.property_type}</span></div><b>{p.rent}</b><span className={`verify-pill ${p.verified?"yes":""}`}>{p.verified?"✓ Verified":"Unverified"}</span><button onClick={()=>verifyProperty(p)}>{p.verified?"Remove badge":"Mark verified"}</button></article>)}</div>}
 {tab==="analytics"&&<><div className="stat-grid"><div><small>Total leads</small><strong>{leads.length}</strong></div><div><small>Conversion</small><strong>{conversion}%</strong></div><div><small>Upcoming visits</small><strong>{upcoming.length}</strong></div><div><small>Verified listings</small><strong>{properties.filter(x=>x.verified).length}</strong></div></div><div className="analytics-grid"><div className="data-card"><div className="data-head"><b>Lead status funnel</b></div>{statuses.map(s=>{const n=leads.filter(x=>x.status===s).length;return <div className="bar-row" key={s}><span>{s.replaceAll("_"," ")}</span><i><b style={{width:`${leads.length?n/leads.length*100:0}%`}}/></i><strong>{n}</strong></div>})}</div><div className="data-card"><div className="data-head"><b>Locality-wise demand</b></div>{localityRows.slice(0,8).map(([name,n])=><div className="locality-row" key={name}><span>{name}</span><strong>{n} lead{n===1?"":"s"}</strong></div>)}</div></div></>}
 </section></main>;
}

function VisitCard({lead,update}:{lead:Lead;update:(id:string,changes:Partial<Lead>)=>Promise<void>}){const [when,setWhen]=useState(lead.scheduled_at?new Date(new Date(lead.scheduled_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):"");const [notes,setNotes]=useState(lead.visit_notes||"");const reminder=`Hi ${lead.full_name}, this is a reminder from Pixellar Spaces${lead.property_title?` for your visit to ${lead.property_title}`:""}${when?` on ${fmt(new Date(when).toISOString())}`:""}. Please confirm your availability.`;return <article className="visit-card"><div><span className="lead-type">VISIT</span><h3>{lead.full_name}</h3><p>{lead.property_title||lead.locality_budget||lead.city}</p></div><label>Date & time<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><label>Visit notes<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Meeting point / agent"/></label><div className="visit-actions"><button onClick={()=>update(lead.id,{scheduled_at:when?new Date(when).toISOString():null,visit_notes:notes,status:when?"visit_scheduled":"contacted"})}>{lead.scheduled_at?"Reschedule":"Schedule"}</button><a target="_blank" href={`https://wa.me/91${lead.phone.replace(/\D/g,"").slice(-10)}?text=${encodeURIComponent(reminder)}`}>WhatsApp reminder</a>{lead.scheduled_at&&<button className="danger-link" onClick={()=>update(lead.id,{scheduled_at:null,status:"contacted",cancellation_reason:"Cancelled by admin"})}>Cancel</button>}</div></article>}
