"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";

const plans=[
 {code:"owner_starter",name:"Owner Starter",price:999,featured:false,features:["1 active listing","30-day visibility","Enquiry tracking","Renew anytime"]},
 {code:"owner_featured",name:"Owner Featured",price:1999,featured:true,features:["Up to 3 active listings","Featured placement","Verification eligibility","Priority follow-up"]},
 {code:"broker_pro",name:"Broker Pro",price:4999,featured:true,features:["Up to 15 active listings","Featured placement","Lead and visit dashboard","Priority support"]},
];
declare global { interface Window { Razorpay?: new (options:Record<string,unknown>)=>{open:()=>void}; } }
export default function PlansPage(){const [chosen,setChosen]=useState<(typeof plans)[number]|null>(null),[notice,setNotice]=useState("");
 async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!chosen)return;const d=new FormData(e.currentTarget);setNotice("Preparing secure payment…");const response=await fetch("/api/payments/create-order",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan_code:chosen.code,customer_name:d.get("name"),customer_phone:d.get("phone"),customer_email:d.get("email"),account_type:chosen.code.startsWith("broker")?"broker":"owner"})});const order=await response.json();if(!response.ok){setNotice(order.error||"Payment setup is not active yet.");return}if(!window.Razorpay){await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve();s.onerror=()=>reject();document.body.appendChild(s)})}new window.Razorpay!({key:order.key,amount:order.amount,currency:"INR",name:"Pixellar Spaces",description:chosen.name,order_id:order.order_id,prefill:{name:d.get("name"),email:d.get("email"),contact:d.get("phone")},theme:{color:"#ea6b36"},handler:async(payment:Record<string,string>)=>{const verified=await fetch("/api/payments/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payment,checkout_id:order.checkout_id})});const result=await verified.json();setNotice(verified.ok?`Payment successful. Your ${chosen.name} plan is active.`:result.error||"Payment verification failed.")}}).open()}
 return <main className="plans-page"><nav className="plan-nav"><Link className="brand" href="/"><span className="brand-mark">P</span><span>Pixellar <b>Spaces</b></span></Link><Link href="/">Back to listings</Link></nav><section className="plan-hero"><span className="kicker">LIST MORE · REACH FASTER</span><h1>Plans for owners and brokers</h1><p>Choose a transparent monthly plan. Payments are secured by Razorpay and renewals stay under your control.</p></section><section className="plan-grid">{plans.map(p=><article className={p.featured?"plan-card popular":"plan-card"} key={p.code}>{p.featured&&<span className="plan-tag">POPULAR</span>}<h2>{p.name}</h2><div className="plan-price">₹{p.price.toLocaleString("en-IN")}<small>/month</small></div><ul>{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul><button className="orange-btn" onClick={()=>{setChosen(p);setNotice("")}}>Choose {p.name}</button></article>)}</section>{chosen&&<div className="modal-backdrop" onMouseDown={()=>setChosen(null)}><form className="modal payment-modal" onSubmit={pay} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setChosen(null)}>×</button><span className="kicker">SECURE CHECKOUT</span><h2>{chosen.name} · ₹{chosen.price.toLocaleString("en-IN")}</h2><label>Full name<input name="name" required/></label><label>Phone number<input name="phone" required inputMode="tel"/></label><label>Email address<input name="email" required type="email"/></label>{notice&&<div className="dash-notice">{notice}</div>}<button className="orange-btn">Continue to Razorpay</button><small>By continuing, you agree to the subscription and refund terms.</small></form></div>}</main>}
